name: Nadia Django

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest #use the web server system
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python ${{matrix.python-version}}
        uses: actions/setup-python@3
        with: 
          python-version: ${{matrix.python-version}}
      - name: Install dependencies class !! yay!!
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run the test baby!
        run:
          python manage.py test


